version: "3"

services:
  app:
    image: express_deploy
    build:
      context: .
    volumes:
      - ./app/:/opt
      - node_modules:/opt/node_modules
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ./config/config.json:/opt/app/config/config.json
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

volumes:
  node_modules: